bool bt_cancelMission
bool bt_passHand
bool bt_passAuto	
bool bt_clearError
bool bt_setting

bool bt_speaker
bool bt_charger
bool bt_brake

bool bt_forwards
bool bt_backwards
bool bt_rotation_left
bool bt_rotation_right
bool bt_stop

bool bt_agv11_arrived
bool bt_cy11_receive
bool bt_cy11_stop
bool bt_cy11_push

bool bt_agv12_arrived
bool bt_cy12_receive
bool bt_cy12_stop
bool bt_cy12_push

bool bt_agv21_arrived
bool bt_cy21_receive
bool bt_cy21_stop
bool bt_cy21_push

bool bt_agv22_arrived
bool bt_cy22_receive
bool bt_cy22_stop
bool bt_cy22_push

bool bt_agv1stfloor_arrived
bool bt_cy1stfloor_receive
bool bt_cy1stfloor_stop
bool bt_cy1stfloor_push

bool bt_agv2ndfloor_arrived
bool bt_cy2ndfloor_receive
bool bt_cy2ndfloor_stop
bool bt_cy2ndfloor_push

bool bt_speakerSound_1
bool bt_speakerSound_2
bool bt_speakerSound_3

bool bt_light_red
bool bt_light_green
bool bt_light_blue

#bool bt_toyoWrite_1
#bool bt_toyoWrite_2
#bool bt_toyoWrite_3
#bool bt_toyoWrite_4
#bool bt_toyoWrite_5
#bool bt_toyoWrite_6
#bool bt_toyoWrite_7
#bool bt_toyoWrite_8
#bool ck_enable_link
bool bt_linkConveyor
int16 vs_speed
bool bt_resetFrameWork
