bool bt_cancelMission
bool bt_passHand
bool bt_passAuto	
bool bt_clearError
bool bt_setting

bool bt_speaker
bool bt_charger
bool bt_brake

bool bt_forwards
bool bt_backwards
bool bt_rotation_left
bool bt_rotation_right
bool bt_stop

bool bt_cy1_received
bool bt_cy1_stop
bool bt_cy1_transmit

bool bt_cy2_received
bool bt_cy2_stop
bool bt_cy2_transmit

bool bt_cy3_received
bool bt_cy3_stop
bool bt_cy3_transmit

bool bt_cy4_received
bool bt_cy4_stop
bool bt_cy4_transmit

bool bt_cy5_received
bool bt_cy5_stop
bool bt_cy5_transmit

bool bt_cy6_received
bool bt_cy6_stop
bool bt_cy6_transmit

bool bt_speakerSound_1
bool bt_speakerSound_2
bool bt_speakerSound_3

bool bt_light_red
bool bt_light_green
bool bt_light_blue

bool bt_toyoWrite_1
bool bt_toyoWrite_2
bool bt_toyoWrite_3
bool bt_toyoWrite_4
bool bt_toyoWrite_5
bool bt_toyoWrite_6
bool bt_toyoWrite_7
bool bt_toyoWrite_8
bool ck_enable_link
int16 vs_speed
bool bt_resetFrameWork